apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
  namespace: kubernetes-cluster-nitingoyal
  labels:
    app: node-app-service
spec:
  strategy:
    type: RollingUpdate
  replicas: 4
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        image: nitingoyal/samplenodeapp:latest
        envFrom:
        - configMapRef:
            name: db-configs
        - secretRef:
            name: db-credentials
        resources:
          requests:
            memory: "250Mi"
            cpu: "250m"
          limits:
            memory: "250Mi"
            cpu: "500m"
        ports:
        - containerPort: 7100

---
apiVersion: v1
kind: Service
metadata:
  name: node-app-service
  namespace: kubernetes-cluster-nitingoyal
  labels: 
    app: node-app-service
spec:
  type: LoadBalancer
  selector:
    app: node-app
  ports:
    - port: 80
      targetPort: 7100
